### ISSUE TITLE
Adding a boost mode to 450C

### ISSUE THREAD

**Issue by OtterNas3** [Ralim/ts100#10]
Just a short question if it would be possible to crank up the max temp to 450, only for a short period maybe 1 minute or 2 then fall back to 400 to not burn out the heater?

Appreciate your work here ;)

**Comment by Ralim** [comment]
It should be possible technically. I just have no idea how the tip will handle the higher temperatures.
How would you propose activating such a feature? I'm more than happy to look at creating a test build so that you can test the higher temperatures on your iron, I just can't see and easy way to integrate this into the control scheme of the iron when you are soldering?

Thank you :)

**Comment by Maartenwut** [comment]
I run mine on 450 a lot of the time, works without a problem! (Though the body will get a little warm after a while)

**Comment by Ralim** [comment]
Awesome :)
I'm glad to hear the 450 degrees doesn't cause too much of an issue.
Any idea how best to have the boost mode added to the software?

**Comment by OtterNas3** [comment]
Hey Guys,

maybe it is possible to make a Double-Tap on the button next to the tip in Soldering mode, then it cranks up to 450 for set time (maybe even configurable in the settings menu)?

**Comment by Ralim** [comment]
Hmm sounds like a possible way to handle it.
Unfortunately, I'm fairly tied up until end of next week so may not be able to add it until then :(
More than open to any other suggestions on how to handle this, though double tap probably makes the most sense. Would another option be to have it detect holding the front button and have it boost the temp while you hold the button?

Or we could even go for just having it drive the tip at maximum while you hold the button for when you have one of those big solder jobs?

**Comment by OtterNas3** [comment]
Isn't the Hold-Down of that button alrdy a function?

**Comment by Ralim** [comment]
Not currently, pressing either button takes you to the temperature screen, and pressing both at once exits soldering. I could add a boost mode to long holding the button.

To compile, I use System Workbench from openstm32.org. You should be able to import the workspace folder into it. However, I do plan to document this better on the wiki... Though if you do get the code compiling I would appreciate anyone who would like to write it up :)

**Comment by OtterNas3** [comment]
I'll give it a try!

**Comment by Bucknalla** [comment]
Just seen this - I'm also happy to help with a write-up!

**Comment by Ralim** [comment]
Hi, @OtterNas3 
I've been thinking on this, would it be acceptable to add an option to just remap the button near the tip to a temporary 450C boost mode? This would make it so that only the other button could enter the temperature settings screen. I could build a firmware fork for testing this option if that could work.
Mostly just because I haven't had the time to re-code the code for button handling yet.

**Comment by OtterNas3** [comment]
@Ralim 
That would be totally fine, as you normally dont change the temp that often.
I would make it like a Hold-For-Boost button, and if possible Double-Tap for Temp setting.
Tried alrdy to implement but, i am not rly a good coder, more a Hardware guy :)

Thanks for getting into it!

**Comment by Ralim** [comment]
I'll make it a hold for boost (Its easiest) 😀 
Yeah, no problem, I'm not amazing, but I get there eventually :)

**Comment by Ralim** [comment]
Let me know if you have any further ideas for this (aka feel free to re-open the issue if you have more ideas)

**Comment by OtterNas3** [comment]
Tested and it works beautyful!
