### ISSUE TITLE
Use Y/N instead of T/F

### ISSUE THREAD

**Issue by ulab** [Ralim/ts100#168]
It took me a moment to realize what the T/F settings meant... Perhaps it's better to use Y/N (Yes/No) instead?

**Comment by Mrkvozrout** [comment]
@ulab Hi, do you mean english or other language? This is currently up to each language translation (translator's choise).

**Comment by ulab** [comment]
English. I have installed the firmware without any language extension. (I'm still guessing T stands for True and F for False? :-))

This is something coders might realize, but for the "common people", I think Yes and No might be easier.

It's just a suggestion since it was the first thing that came to my mind yesterday.

**Comment by Mrkvozrout** [comment]
Thanks to bring in your opinion and (re)start the discussion.

It is hard to decide what indication to choose (true/false, yes/no, +/-...). I think the commonly most realizable would be to implement ✓✗ characters. I will try to play with it and share results (if someone wouldn't be faster :) ).

**Comment by matmemo** [comment]
I had a similar feeling as ulab when I did the german translation. In english it's kind of ok for me because it feels quite natural in a technical context if you've done some programming. But translated to german it really get's awkward. The English letters feel out of place and the german equivalent W/F isn't used in devices I know of and I doubt anybody would understand these letters at first glance anyway.

What I'm getting at is my favourite solution up to now. With the new double line mode for the settings it's posible to simply pose the concerned setting as a question, ending with a question mark. After that it's quite clear that I have to answer Yes or No (J/N in german).

Well that's just my two cents on the matter and I'd really like to know what others are thinking about that idea.

**Comment by Mrkvozrout** [comment]
@matmemo I think that is really good solution. In my czech translation I bet on when users don't not know what the values are, they wait (or stare in confusion :D) until the description shows and they can read what thhe options mean.

What do you think about the ✓✗ chars?

**Comment by Rockman18** [comment]
I've pushed a pull request #177 proposing a checkbox instead of T/F or Y/N

**Comment by SilverSho0t** [comment]
I think ✓✗ characters are a very good solution. It will simplify the menu.

**Comment by MichMich** [comment]
My first though would be ✓✗as well.

**Comment by wortex1979** [comment]
i think ✓✗  characters is very good

**Comment by Rockman18** [comment]
Pull Request #177 add a checkbox intead of True/False. This PR has been merged in master last week but not compiled/released yet. The checkboxes look like that : ![checkbox_off](https://user-images.githubusercontent.com/1739183/34320837-75b47c76-e802-11e7-9738-3fa246a68984.png) ![checkbox_on](https://user-images.githubusercontent.com/1739183/34323273-8dcf3b4a-e841-11e7-8397-7bd0e82da1cd.png)

I've compiled a V2.02-alpha.1 in English to share it with you. Tell me your opinion for thoses checkboxes.

[TS100_v2.02-alpha.1_EN.zip](https://github.com/Ralim/ts100/files/1594421/TS100_v2.02-alpha.1_EN.zip)

**Comment by SilverSho0t** [comment]
Very nice @Rockman18 much more understandable & user friendly ;)

**Comment by MichMich** [comment]
Look much better than the T/F. Awesome. You might want to add a bit of margin at the bottom so that it is better aligned to the inter of the screen.

**Comment by Mrkvozrout** [comment]
@Rockman18 good work, you were faster :)

I offer my pull request #183 with updated checkboxes with discussed ✓✗ chars. I think it looks neater and even more understandable (as the X looks more descriptive then current empty chackbox).

What do you guys think? (see PR for photos)
