### ISSUE TITLE
Actual Sleep timeout is 1 minute longer than the set value

### ISSUE THREAD

**Issue by jonnieZG** [Ralim/ts100#189]
Actual Sleep timeout is 1 minute longer than the set value. I.e. if the Sleep time is set to 1 minute, the device will go into sleep mode after 2 minutes of being still.

**Comment by Ralim** [comment]
Hi,
Yes this is still on the todo list, I have a rough workaround implemented, but its taking time to test *every* time related bit of code on the unit. This should be fixed in any further releases though, as I havent found any issues in a fair while now.

I stopped pushing out as many alpha releases as its alot more upkeep to track.
If you wish I can push an alpha for this one tomorrow
