### ISSUE TITLE
A different approach to the boost mode

### ISSUE THREAD

**Issue by twikis** [Ralim/ts100#26]
I like the boost feature, however I find that always need to change the temperature when going up/down with the main temperature depending on what I'm soldering.

How about making the boost "additive", meaning when the iron is set to 270C you can temporarily add 50C to it? Or when you set the boost to 30°, it goes from 270C to 300C. In my opinion a range from 0C to 100C is enough (also frees up another menu entry).

Thoughts?

**Comment by Ralim** [comment]
The vast majority of users rarely change their operating temperature on the iron. Most people use 360C for soldering normally, and then a higher temp such as 400C for the boost mode. As this provides a high level of flexibility for soldering almost all joints. 

The boost mode was mostly added as a method of being able to pre-emptively boost the soldering irons temperature before soldering a joint with a high thermal mass. 

I don't really see a large point to having it work as an offset since it's meant to be used on high thermal situations where you need the higher temp. For most smaller work just waiting an extra second for the tip temperature to recover should be enough?

What kind of joints are you soldering that causes you to need to keep adjusting the temperature so much?

I'm not opposed to this, I just don't see a need to go to a more complex for the user scenario?
Adding menu entries is basically free, so there's no need to reduce menu options *yet*.

I was originally just going to have the boost mode always set to 400C, but some users wanted the higher temperature ranges available.
