### ISSUE TITLE
Binary releases no longer available

### ISSUE THREAD

**Issue by lorenz** [Ralim/ts100#414]
I run DAPBoot as DFU bootloader. Since switching to per-language releases it looks like the binary releases are no longer published on GitHub. This is pretty annoying for people not using the stock bootloader.

* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Workaround** 

```
arm-none-eabi-objcopy -I ihex --output-target=binary TS100_EN.hex TS100_EN.bin
```

**Comment by dogtopus** [comment]
I agree it is pretty annoying for DAPBoot users (In fact I am also using DAPBoot on my TS100). However the problem is that the release page is already pretty crowded due to the number of multi-language firmwares. It would probably be worse if binary versions are also provided. For this reason I always build my own binary using the Makefile instead of relying solely on the release.

**Comment by JohnEdwa** [comment]
Seeing as all of the current .HEX releases combined are only around 2.5MB, grouping all the non-english language releases to a single .zip file could clean the release page while really not making that much of a difference. Although the filename would be pretty funny with all the 20 or so language codes back to back.

So:

* TS100_EN.HEX - 130KB
* TS100_EN.BIN - 130KB
* TS100_BG_BR_CZ_DE  ...  TR_UA.ZIP - ~5MB

**Comment by lorenz** [comment]
I also used to build my own but none of mine work, probably due to some undefined behavior and GCC 8 behaving differently. So I'm kind of stuck using the officially built ones.
