### ISSUE TITLE
TS80 Flashing failure on Windows 10

### ISSUE THREAD

**Issue by Red-M** [Ralim/ts100#439]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
Reporting a bug

* **What is the current behavior?**
Windows 10 seems to cause a failure with flashing

* **What is the expected behavior?**
Windows 10 flashes the iron

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

I followed the steps exactly as the flashing guide said and it would not flash. Instead it would disconnect immediately as I tried to copy the file to the iron.

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.x
  - PCB Version: (1/2) TS80
  - Power Supply (Voltage and Current Rating) :

* **Other information** 
I had to flash via linux to get the iron to boot again.

**Comment by Ralim** [comment]
Sadly I cant fix issues with the bootloader :(
On windows you have to use windows explorer with no anti-virus that mitm's the file copy. You also cant use any other file copy tools.

**Comment by Red-M** [comment]
Yeah I had AV off and was using just plain explorer, the issue is that
Windows 10 has the buffered copy built in.

**Comment by Ralim** [comment]
@Red-M Windows 10 worked perfectly fine for me for over a year, and works totally fine for lots of other people. It *doesnt* use buffering on FAT12 and FAT16 devices, only FAT32 and newer, so it doesnt buffer writes to this DFU. No idea why yours didnt work then. :/

**Comment by omair94** [comment]
I'm having this issue as well. It worked fine a month ago, but now that I have done a fresh install of Windows, the soldering iron now disconnects before the file transfer is done. 

Something must have changed in a recent Windows update or something.

**Comment by DjordjeMandic** [comment]
I had to do it on win xp, it always shows err then flashing it again without deleting err file fixes the rpoblem.

**Comment by whitehoose** [comment]
The double dip is pretty standard, aggravating but normal.  Windows has write caching on by default.  This is windows trying to be helpful, when you copy a file, quite a complex set of processes kick in so good old windows tells you it's all done ... when in fact what its done is copy the file into cache, then when it thinks you're not looking (ie not stressing the processor) - it actually then transfers the file.  All this so you never experience slowdowns.
With external drives - if you are a bit too quick, you copy ... unplug and corrupt or lose the file.
In theory caching should auto disable on USB devices - but it doesn't always.  Since win 95 I configure external devices to switch write caching off | in explorer right click the drive | properties | hardware | select ts80 | properties | change settings | policies | untick write caching.
Also disable indexing if it's ticked.
You only need check once.  You'll still need the double dip - but you'll know nothing else is working against you.

**Comment by DjordjeMandic** [comment]
@whitehoose Well it was disabled thats the probelm... But why i need to flash hex 2 times?

**Comment by whitehoose** [comment]
If cache disabled (It's worth checking on any external device).  That's really the only system thing that can screw with copies (generic USB drivers are very rarely culprits).
The FW update process just works like that - the double dip is not a fault - it's just a foible.
Windows is 1000s and 1000s of bytes worth of code in a system that's probably got 60% storage and 80% of system resources free most of the time to tell you chapter and verse about every passing thought.
That little iron however has a couple of 100 bits spare and so has to make every bit of code, memory etc count.  That tends to mean error messages are a terse couple of words that cover 100s of possible states.
(20 years ago if you'd said a soldering iron would need a processor to make it work ppl would have laughed) - I still wonder sometimes what was wrong with a simple element, no logos or display - if the solder melts - it's working!.
Its a very long worded way of saying that's just how it is - noting to see here.

**Comment by DjordjeMandic** [comment]
@whitehoose If you have ts80 can you please check this?
![image](https://user-images.githubusercontent.com/6750655/57974041-4d53fc00-79b2-11e9-9e36-b7c96c5ba093.png)
I think that there's something wrong with my iron not the firmware.
