### ISSUE TITLE
Question on adding feature request

### ISSUE THREAD

**Issue by Reydan46** [Ralim/ts100#443]
Is it possible to calibrate the temperature of the sting manually, setting the temperature of the room?

1. Using a third-party thermometer, we measure room temperature.
2. The resulting value is set manually on the soldering iron.

The current simple calibration (with the TS100 BC100 tip parameter set) sets the temperature to 33 degrees Celsius (the actual room temperature is 24 degrees Celsius).

P.S
Sorry for my bad English (I use a translator)

**Comment by Ralim** [comment]
This could certainly be done, but honestly doesn't usually help all that much, since you would need to do a multiple point calibration to adjust both the offset and gain of the temperature sensor inside the handle. Then this can be used for a more accurate reading of the tip.

If you have access to a thermal chamber that could do a multiple point calibration of the handle (say 3 points, 0C,15C,30C) then it could be possible to support this. But I feel that most people do not have the equipment for this.
