### ISSUE TITLE
Hint: use normal windows copy - using "Copy Handler" results in ERR file when updating

### ISSUE THREAD

**Issue by bl4k1st** [Ralim/ts100#544]
A problem I stumbled upon:
I had trouble updating my TS100.
I always got a ERR file.

Reason was I am using "Copy Handler". Copying the file with normal windows copy worked, the iron updated and I got a RDY file.

Perhaps you want to edit that in Readme install notes.

**Comment by whitehoose** [comment]
Don't know if I'm misunderstanding I normally use linux - so rarely update from windows - but for me - a "normal" update sequence using either windows or linux is: Plug Iron in (holding button a) - file manager window opens DFU shows on iron - drop update into window ... window closes then opens displaying .err file .... ignore drop update file again - window closes pause .... then opens.
Recycle iron 
Check update OK
Its done this from day one. Linux NEVER shows a .rdy - windows tends to - but an impatient restart doesn't but still does the job.
because there is so little system space for frills - the messages are as misleading as the early DOS or windows errors.
The important thing is getting the new version number after second restart.

**Comment by Ralim** [comment]
@bl4k1st There is a long discussion github issue about this (well many issues that get spawned).
It is also noted over in the [wiki](https://github.com/Ralim/ts100/wiki/Upgrading-Firmware) that using file copiers such as teracopy will break things.

I will try and add it to the wiki as well
