### ISSUE TITLE
Couple of bugs in 2.08.1 - cosmetic

### ISSUE THREAD

**Issue by Miwer** [Ralim/ts100#566]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **What is the current behavior?**
After upgrading my TS100 from 2.05 to 2.08, I noticed some small cosmetic bugs:
1. Autostart setting allowed values are: F, T, S - but help text states "A=Soldering, S=Sleep mode, M=off"
2. When tip is disconnected, detailed idle screen shows tip temperature of 417 degree C instead of "tip disconnected". Could be mistaken for a regulating problem, if there's a loose connection.
3. When soldering, tip temperature drops during changing of set temperature. It seems like the iron is not powering the tip when operating the buttons. (not sure it has always been like this, I didn't notice this on the older version)

* **What is the expected behavior?**
1. Help text matched to the available options.
2. "tip disconnected" message when no tip is inserted. 
3. Iron maintaining constant temperature when operating buttons.

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.08
  - PCB Version: 2
  - Power Supply : DC 20V 65W

* **Other information**

Using the English firmware TS100_EN.hex

Cheers :)

**Comment by Ralim** [comment]
Hi,

1. -> 

has been fixed since release, so will be fixed once it's released.


2.  ->
Was a conscious decision to remove this as to allow tip regulation all the way up to whatever the maximum the ADC can read for your calibration settings.

3. ->

This has always been the way, to play it safe, so that if you want 200C but you last used it at 400C it's not already at 300C by the time you get down to 200C
